### ISSUE TITLE
Google link not correct

### ISSUE THREAD

**Issue by bitasy** [googlesamples/android-NetworkConnect#1]
The app is supposed to fetch raw html from Google. The url it uses is "http://www.google.com", but this results in a 302 Moved message being printed in the logger (the app still works perfectly fine). When I changed the address to "https://www.google.com/?gws_rd=ssl", as the message recommended, it worked perfectly, and the HTML shown was the beginning of the meta tags for google. Note that I am referring to the address entered as a parameter to the new DownloadTask().execute() method in MainActivity.java.

**Comment by tjohns** [comment]
Thanks, I'll take a look at this.

**Comment by tjohns** [comment]
I was unable to reproduce this.

It probably would be good to add redirect handling for robustness, but it seems to work correctly (at least for me).
