### ISSUE TITLE
issue importing from Android Studio 1.1.0

### ISSUE THREAD

**Issue by sreev** [googlesamples/android-NetworkConnect#2]
Fresh install Android Studio 1.1.0
Quick Start menu
Import an Android code sample
Connectivity->Network Connect
Next
Fails.

This is due to the reason the Android Studio 1.1.0 comes installed with Android SDK Build-tools v21.1.2.
Refer to SDK Manager.

But this project requires minimum v21.1.1.
The work around is, before importing code sample,  go to SDK Manager and install build-tools v21.1.1.

Which is not user friendly and definitely not a newbie friendly.

**Comment by sreev** [comment]
created pull request:
https://github.com/googlesamples/android-NetworkConnect/pull/5

**Comment by tjohns** [comment]
This will be fixed with our next bulk samples update, likely early next week.
