### ISSUE TITLE
bump up minSdkVersion from 8 to 11 (android v3)

### ISSUE THREAD

**Issue by sreev** [googlesamples/android-NetworkConnect#4]
Current Adroid v5 backwards supporting until android v3; seems fair.

**Comment by sreev** [comment]
created pull request:
https://github.com/googlesamples/android-NetworkConnect/pull/5

**Comment by tjohns** [comment]
I'm not sure I understand what this issue here is. The app runs correctly on Gingerbread.

**Comment by keyboardsurfer** [comment]
Looks good from my POV as well.
Closing this issue.
Feel free to re-open with a comment on why this version bump might be necessary.
